### ISSUE TITLE
Support for BibTeX "entry types"

### ISSUE THREAD

**Issue by kerim** [sawhney17/logseq-citation-manager#10]
Ideally an app of this kind would support the full range of [14 entry types](https://www.bibtex.com/e/entry-types/) in the BibTex format. That would mean two things:

1. Being able to use a {type} placeholder in templates which would enter "book," "article," ''MA Thesis" etc. 
2. Producing differently formatted inline note templates depending on the type. For instance, a book might be:  `{author}. {year}. *{title}*. {address}: {publisher}.` Whereas a journal article would be: `{author}. {year}. "{title}." *{journal}* {volume} ({number}): {pages}.`

1 seems a lot easier than 2, but is very useful because one can then filter one's literature notes by type if this is included in the page metadata. 2 might be something to think about for future development. For now I have a template which lists both and then I delete the incorrect one.

**Comment by sawhney17** [comment]
1. Should already be working. 
2. This would not be possible in the current settings view of logseq. This would require manually editing a json file to create this. Similar to how the banners plugin implements custom links based on page types. Would that work?

**Comment by kerim** [comment]
I don't mind editing the JSON file - for new users you'd probably want to have some default settings. 

I'll test out 1 again.

**Comment by sawhney17** [comment]
Can you specify one source that doesn't work with type?

**Comment by kerim** [comment]
I can't get {type} to work with any citation. I've tried several books and articles and it is always just blank.

**Comment by sawhney17** [comment]
Are other changes made to your template persisting?

Try reindexing?

**Comment by kerim** [comment]
I entered the following line:
source:: {type}

and I get:
source::

So it isn't that.

**Comment by kerim** [comment]
This issue is fixed, right?
