### ISSUE TITLE
Custom template for inserting link to note

### ISSUE THREAD

**Issue by kerim** [sawhney17/logseq-citation-manager#11]
Right now the link to note option enters [[citekey]]. I'd like to have something more like this: `[({author lastname} {year})]([[citekey]])` which would show up as (author year) but work as a link to the page. It is just more readable in my notes if it is done that way, and I can manually add the page number in there if I need to.

**Comment by sawhney17** [comment]
At the moment, you can customise the title from the settings, but I just added an option to customise an optional alias in settings.
