### ISSUE TITLE
[Question] Does The User Have Any Control Over The Page Title?

### ISSUE THREAD

**Issue by rsomani95** [sawhney17/logseq-citation-manager#16]
Specifically, can one add a prefix `@` to the start of each title? Both the Obsidian plugin and the official Zotero plugin do this by default. I find it makes it a lot easier to find the zotero links and keeps pages cleaner.

Is this something the user has control over, or is hard coded?

**Comment by sawhney17** [comment]
In settings, you can change the pageTitle format.

**Comment by rsomani95** [comment]
Ah. I missed that. Thanks, that fixes it.
