### ISSUE TITLE
[Bug] mod+shift+I opens the DevTools

### ISSUE THREAD

**Issue by davidjaggi** [sawhney17/logseq-citation-manager#21]
When pressing mod+shift+i, the dev tools side panel is also opened.

![image](https://user-images.githubusercontent.com/23697632/178454800-f7618930-bc99-47e6-83f8-30e927b65b3e.png)

**Comment by davidjaggi** [comment]
Maybe you can allow for alternative shortcuts.

**Comment by sawhney17** [comment]
You can now update shortcuts
