### ISSUE TITLE
[Enhancement] Allow search not only on title but also on author and other content

### ISSUE THREAD

**Issue by davidjaggi** [sawhney17/logseq-citation-manager#24]
Currently, I need to remember the title of the publication. It would be nice to also see the year and authors of the paper and allow to search for them.

**Comment by jacobtfisher** [comment]
+ 1 for this as well. I often search by author, so it was odd at first to not not see things come up when I put in the author's name.

**Comment by L0cast** [comment]
+1 for this, please allow search by author.

**Comment by sawhney17** [comment]
Will be coming shortly!

**Comment by carljoseph** [comment]
Search **and** display the author and perhaps year would be amazing. I often search by author & year "Toomre 1977". 

Display is important too, especially when you have multiple resources titled the name thing

<img width="931" alt="Screen Shot 2022-09-25 at 9 01 11 pm" src="https://user-images.githubusercontent.com/4588120/192188649-b1486a5a-a75c-4627-a3ab-5cd59577a0ea.png">

**Comment by sawhney17** [comment]
Supported searching by author as well now!

**Comment by reox** [comment]
> Supported searching by author as well now!

works like a charm!
Together with the year or citationkey and maybe journal title, it would be perfect <3

Interestingly, I noticed that the search seems to be case sensitive and I have to type the names lowercase, although the names are uppercase in the bib file. I.e., if the name is `Example`, it would only be found if I type `example`.

**Comment by sawhney17** [comment]
Ooh, interesting. Is this with or without the SmartSearch feature enabled in settings?

**Comment by reox** [comment]
without the smart search. Unfortunately, I have so many items in the library that with it enabled, it takes too long to find anything :D

**Comment by sawhney17** [comment]
Quick question. Do you by chance have the index abstract option ticked? If so that's the reason behind poor performance in smart search.

**Comment by sawhney17** [comment]
Just released an update with improved performance on smart search.

**Comment by sawhney17** [comment]
And just pushed another release fixing case sensitive search when not in smart search

**Comment by reox** [comment]
> Quick question. Do you by chance have the index abstract option ticked? If so that's the reason behind poor performance in smart search.

I had both disabled. Some time last year I played around with it and had poor performance on my machine, but I can test again - maybe it has changed in between!
Thanks for the fixes!
