### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: Cannot read properties of null (reading 'forEach')

### ISSUE THREAD

**Issue by liberix** [sawhney17/logseq-citation-manager#32]
When I try to use the command to insert the citation, only "inserting..." is shown on the block and the console give the error:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'forEach')
    at fS (/Users/chrix/.logseq/plugins/logseq-citation-manager/dist/assets/index.fdbc58e0.js:120)
    at async np (/Users/chrix/.logseq/plugins/logseq-citation-manager/dist/assets/index.fdbc58e0.js:120)
```
I am using MacOS, and the logseq version is 0.8.0

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/68191508/184377030-d16a6e98-c2be-47c2-a18b-f7182ab30bc6.png">

**Comment by sawhney17** [comment]
Set a template in plugin settings.

**Comment by liberix** [comment]
Hi, thanks for reply. Inserting page works now, but inserting a block still shows nothing. 

The template for block is 
```
- {title} by {author}
template:: citation-block
```

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/68191508/184470349-1a4df1ad-1ad1-4e28-a8af-cf58b1d277ef.png">

**Comment by sawhney17** [comment]
Have you written citation-block in the settings? Perhaps try a name without a dash.

**Comment by liberix** [comment]
I put the "citation-block" in the settings and a name without dash cannot work either. Actually, the page template with a dash works fine. 

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/68191508/184475821-9733fbeb-7c95-4191-8505-72d756a4db4a.png">

**Comment by sawhney17** [comment]
Can you send a screenshot of the template?
And possibly the settings screen as well.

**Comment by liberix** [comment]
Here is the template:

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/68191508/184486945-3d886165-661e-4ec6-944e-1659861c19b5.png">

And here is the settings:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68191508/184487541-8f8635ce-e6ed-46de-9134-d3ad92f244c0.png">


Thanks

**Comment by sawhney17** [comment]
You have to indent your actual template underneath the template:: citatinBlock block

**Comment by liberix** [comment]
It works now. Thanks
