### ISSUE TITLE
Citation manager does not work anymore with logseq 0.8.1

### ISSUE THREAD

**Issue by menelic** [sawhney17/logseq-citation-manager#33]
@sawhney17 hinted that it has to do with logseq switching to new electron...hopefully there is a quick fix to keep this key plugin working with current logseq versions

**Comment by carljoseph** [comment]
Same for me. v0.8.2 just prints out "inserting..."

**Comment by sawhney17** [comment]
Waiting for the next update to have a key api that would allow me to refactor the plug-in.

**Comment by Feivele** [comment]
Alternative solutions meanwhile? Revert to previous version or just wait?

**Comment by sawhney17** [comment]
Are any of you on macOS?

**Comment by menelic** [comment]
No, I am on Linux, Ubuntu 22.04 LTS

**Comment by carljoseph** [comment]
I'm on macOS

**Comment by AlexZeitler** [comment]
I'm on macOS

**Comment by Feivele** [comment]
macOS

**Comment by sawhney17** [comment]
Just pushed a new version. You will have to reconfigure the .bib export. It now has to be located in .logseq/storage/logseq-citation-manager and in settings, you just give the filename with extension(like starred-items.bib), no need for the file path.

**Comment by carljoseph** [comment]
Latest version on macOS still has the same problem. It displays the sources in the pop-up but when selecting one it just puts "inserting..." in the text. Same happens regardless of which citation option you select.

**Comment by sawhney17** [comment]
Are you sure you've configured a template?

**Comment by sawhney17** [comment]
Yeah, revert for now is the workaround
