### ISSUE TITLE
No existing db could be found

### ISSUE THREAD

**Issue by zerone01y** [sawhney17/logseq-citation-manager#37]
I've been using the plugin for some time and it worked ok. But recently it seems unable to find the database, even if I reindex the citation db. I did not change any of the settings during the period. Please help, thanks!

**Comment by sawhney17** [comment]
A few versions back broke something so you You will have to reconfigure the .bib export. It now has to be located in .logseq/storage/logseq-citation-manager and in settings, you just give the filename with extension(like starred-items.bib), no need for the file path.

**Comment by sawhney17** [comment]
Excellent idea. I just pushed an update with some fixes for inline insertion. I’ve also updated the readme
