### ISSUE TITLE
no exciting DB could be find

### ISSUE THREAD

**Issue by baresibest** [sawhney17/logseq-citation-manager#38]
I have configed the .bib database .but it displasy no existing DB could be find

**Comment by sawhney17** [comment]
Did you follow the instructions under "Brwaking Change" in the readme?

**Comment by drhaibopan** [comment]
I am using M1 chip MacBook Pro, and I did not find the path: ".logseq/storage/logseq-citation-manager". Would you like to offer me a hand? Thanks

**Comment by sawhney17** [comment]
It’s a hidden folder. Try navigate through it using command shift g in finder. Or by using the shortcut command shift period.  To show hidden folders

**Comment by drhaibopan** [comment]
Thanks for your prompt reply. I did it but still did not find the path.

**Comment by drhaibopan** [comment]
Thanks for your prompt reply. I did it but still did not find the path.

**Comment by drhaibopan** [comment]
BTW, there is a .logseq file but it is not a folder.

**Comment by drhaibopan** [comment]
BTW, there is a .logseq file but it is not a folder. Then, I created ".logseq/storage/logseq-citation-manager" by myself and put  a bib file in it. However, it still does not work. Looking forward to your help.

**Comment by sawhney17** [comment]
Where is this file? It should be on your home folder where the applications and desktop folders are located.

**Comment by drhaibopan** [comment]
First, I deeply thank you very much for your prompt reply and precious time. 
Then, I found the folder under your guide. Previously, I was searching the "file" under iCloud Drive and thus did not find the folder.
However, even if I found the folder, and placed a bib file from Zotero to the correct location, it still does not work. I restart logseq for several times. The only difference is that in my computer, the location is ".logseq/**storages**/logseq-citation-manager" but not ".logseq/_storage_/logseq-citation-manager". Is it the reason?

**Comment by sawhney17** [comment]
Should be storages. What are you writing in the plugin settings?

**Comment by drhaibopan** [comment]
Following the guide, I wrote "zot-library.bib" in settings

**Comment by drhaibopan** [comment]
Glad to tell you that it works now. I do not know why. But thank you very much for your contribution to the plugin, your patience to reply me, and your precious time.
