### ISSUE TITLE
Cannot use arrow keys to select search results

### ISSUE THREAD

**Issue by kerim** [sawhney17/logseq-citation-manager#4]
When searching it seems to only select the first result when hitting enter. But sometimes I might want to select a result further down the list without having to complete the process of filtering for that item. In that case it would be nice to be able to scroll down and select the item, either double clicking on it, or using the arrow keys and then enter.

**Comment by sawhney17** [comment]
You should be able to use the arrow keys to move the active cursor item.

**Comment by kerim** [comment]
Sorry, I should have tested that again after upgrading to the latest version. Yes, it works now.
