### ISSUE TITLE
no citation appearing

### ISSUE THREAD

**Issue by hambo2** [sawhney17/logseq-citation-manager#40]
I have installed the plugin and set up a .bib file as per the instructions. When I try to insert a link to an inline note or literature note, the text "inserting..." appears, but no reference is generated.

**Comment by sawhney17** [comment]
Will be fixed shortly!

**Comment by sawhney17** [comment]
Could this tru update to the latest version?

**Comment by sawhney17** [comment]
Try it on the latest version
