### ISSUE TITLE
Adding property `alias` and setting it to `{citekey}` doesn't work

### ISSUE THREAD

**Issue by richardjlyon** [sawhney17/logseq-citation-manager#47]
In my page template, I have

```
alias:: {citekey}
year:: {year}
filename:: {filename}
```

This does not create an alias for the created page.

**Comment by richardjlyon** [comment]
I’m note sure what you mean.

When I type an alias in directly e.g. alias:: anAlias, then [[anAlias]] will take me to the page.
When alias is set by your plug-in, [[anAlias]] does not take me to the page.

Best wishes

Richard

**Comment by sawhney17** [comment]
I think a Reindex should fix that or alternatively try going tot eh page and click enter after the property is inserted.
