### ISSUE TITLE
how to find the file to storage the DB

### ISSUE THREAD

**Issue by KL2101** [sawhney17/logseq-citation-manager#49]
hi there, I met a problem in the first step, I can't find the file to storage the DB file.

![2022-11-24_abbdE7](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/uPic/2022-11-24_abbdE7.png!upic)

I have read the discuss about this issue, and I have press shift+command+. to open the hidden files, but no such files there.

![2022-11-24_0WoVzF](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/uPic/2022-11-24_0WoVzF.png!upic)

can you help me , thank you!

**Comment by bepolymathe** [comment]
You have to export your bib file in `.logseq/storages/logseq-citation-manager`... It seems (your screenshots) you’re in your graph and not config files ?

**Comment by MatthijsKeep** [comment]
Never mind, the fix for this is in #34 . @JasonX2140

**Comment by kmk93posteo** [comment]
I just started using Ubuntu and I had some problems with this as well. 

What helped me: 
1. find the hidden folder (.logseq), in my case in the home directory, by making hidden folders visible using control + H 
2. give "everyone" (incl Zotero) access to these files by running sudo chmod 777 -c -R .logseq/storages/logseq-citation-manager in the terminal

**Comment by sawhney17** [comment]
In the latest version, the file should be stored in assets/storages
