### ISSUE TITLE
Error message: Template page not found!

### ISSUE THREAD

**Issue by tartakis** [sawhney17/logseq-citation-manager#52]
After installing the plug-in and setting the BibLaTeX library name in the settings, I tried to configure the template files in all possible ways: only file name, file path & file name (pointing inside ~/.logseq/storages/logseq-citation-manager) but to no avail. I get a 'template page not found message'. 

What can I be doing wrong?

**Comment by sawhney17** [comment]
Template page should be a simple page name. Like "template" if that page exists in your graph.
