### ISSUE TITLE
Can't Use Slash Command: Create Inline Literature Note

### ISSUE THREAD

**Issue by li-chena** [sawhney17/logseq-citation-manager#53]
Error log from the console：Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')

![@Logseq Citations Plugin_software 2022-12-31 22-00-34_new](https://user-images.githubusercontent.com/71169759/210155682-45f61488-35f1-4bd4-9182-4076eec7ab17.gif)

**Comment by kmk93posteo** [comment]
For me, "insert inline" and "link to reference" both do not work. All three shortcuts lead me to the selection menu, but after selecting these two options, nothing (useful) happens - I am a layperson, sorry for the bad description. "go to reference" works perfectly fine.

**Comment by kerim** [comment]
I'm having this problem as well. Nothing is happening. I am using 0.8.15

**Comment by sawhney17** [comment]
Was it working in the previous version?

**Comment by kerim** [comment]
I never had such problems before, but I'm also not sure how frequently the versions have updated and whether or not I used it during each version or not. It has probably been about a month since I used it last.

**Comment by kerim** [comment]
This seems to be working again for me now. Perhaps fixed in the last Logseq update?

**Comment by gandalf34** [comment]
I have the same issue.

**Comment by gandalf34** [comment]
https://drive.google.com/open?id=1lqrj0_W--XAmPt6p3JoqwGTm7W1-iqkg

**Comment by kerim** [comment]
Yeah, this seems broken again with the latest update.

**Comment by sawhney17** [comment]
Investigating this.

Sincerely, Aryan Sawhney Homeroom 7.11

**Comment by sawhney17** [comment]
Have you moved the database to the new location in the assets folder?

Sincerely, Aryan Sawhney Homeroom 7.11

**Comment by sawhney17** [comment]
I’ve added a fallback in the latest version, which would prevent the change from breaking workflows.

**Comment by kerim** [comment]
Yes, I moved the database to the new location. Search works, but it won't create anything.

**Comment by sawhney17** [comment]
Try the new update.

**Comment by kerim** [comment]
Seems fixed. Thanks!

**Comment by sawhney17** [comment]
Very stupid error. Used a single equal instead of double equals. Good to see it's fixed.
