### ISSUE TITLE
Search for paper by author name

### ISSUE THREAD

**Issue by Debneil** [sawhney17/logseq-citation-manager#54]
Just wondering, since I couldn't get this to work: am I missing something, or is this not a supported functionality?

**Comment by sawhney17** [comment]
If you enable smart search in settings, you should be able to search the author but I am in the process of revamping the search.

**Comment by sawhney17** [comment]
Correction, that’s not currently there yet. On it though.

**Comment by sawhney17** [comment]
adding it there

**Comment by sawhney17** [comment]
And regular search as well now :)
