### ISSUE TITLE
Citation manager plugin stops working and cant find DB ( I updated to the new folder under assets) only when I rewrite the  bib filename it works.

### ISSUE THREAD

**Issue by gandalf34** [sawhney17/logseq-citation-manager#55]
Citation manager plugin stops working and cant find DB ( I updated to the new folder under assets) only when I rewrite the  bib filename it works.

**Comment by sawhney17** [comment]
Just to clarify what was the steps you took to resolve this?

Typically you just need a reindex.

Sincerely, Aryan Sawhney Homeroom 7.11

**Comment by gandalf34** [comment]
When I rewrite the file name in the settings it can rectify itself

**Comment by gandalf34** [comment]
https://drive.google.com/open?id=1lqrj0_W--XAmPt6p3JoqwGTm7W1-iqkg

**Comment by gandalf34** [comment]
Event with the new update it didn't work. I reindexed to no avail. Changed the file name extension to .bib at first and then to .biblatex and it starts but basically the same errors are still there. Please let me know what info I can provide.

**Comment by sawhney17** [comment]
Try the new update.
