### ISSUE TITLE
Plugin shortcuts giving a conflict error to themselves

### ISSUE THREAD

**Issue by gandalf34** [sawhney17/logseq-citation-manager#56]
![image](https://user-images.githubusercontent.com/86377241/217498171-72290e06-0ab4-417d-bfdc-de539fcd3b9e.png)

I just updated the plugin a few minutes ago and got the attached error message. The shortcuts conflict themselves?

**Comment by sawhney17** [comment]
Shouldn’t be an issue. When logseq updates a plugin, it reregisters all shortcuts without necessarily unregistering the old ones. Restart should fix this if it isn’t working in spite the error

**Comment by gandalf34** [comment]
Yes it doesn't come up after the restart. Just wanted to provide feedback just in case its something important.
