### ISSUE TITLE
Settings page should be more informative about file paths

### ISSUE THREAD

**Issue by paulnov** [sawhney17/logseq-citation-manager#64]
It can help new users to provide examples for where to put the files in the settings page.

e.g. it took me an hour of browsing through the issues and readme (which have contradictory info since a recent update) on where to export the bib DB. Currently it says "enter the path to your DB" which suggests it will be a path, not a filename.

Maybe this text could be changed to "enter the DB filename, including extension. The DB should be stored in `assets/storages/...`"

**Comment by l-d-s** [comment]
Is this `assets/` folder the same as
```
.logseq/plugins/logseq-citation-manager/dist/assets
```
...on Linux?
