### ISSUE TITLE
Duplication error

### ISSUE THREAD

**Issue by kerim** [sawhney17/logseq-citation-manager#8]
When I choose the slash command to insert an inline link to a literature note I expect it to create a single entry [[citekey]] in that block. Instead, it is creating two such entries as child blocks of the current block, which remains empty.

Instead of:

- [[citekey]]

I'm getting

-
  - [[citekey]]
  - [[citekey]]

I'm also getting duplication in the page itself. My template is (after the metadata):

- {author lastname} ({year}),  {title}
  - author
  - {doi}
  - {url}
  - {abstract}

This is all getting duplicated. (But not the metadata.)

Here is a screen recording:

https://user-images.githubusercontent.com/59976/177950130-71ffc3b9-b5b1-494d-a37e-5a78507945cc.mov

**Comment by kerim** [comment]
Ignore the fact that I forgot to wrap "author" in curly brackets in my template. That's just my mistake...

**Comment by sawhney17** [comment]
Looks like when I fixed inline references, I messed up the page ones. Will fix this.
