### ISSUE TITLE
Wrong citation entered

### ISSUE THREAD

**Issue by kerim** [sawhney17/logseq-citation-manager#9]
I cannot reliably reproduce this error, but I'm opening up an issue so that I can add information later if/when I figure out what is going on. Basically, sometimes when I select an item from the list of search results, another item gets entered instead. True of both inline references and inline reference links.

**Comment by kerim** [comment]
After some testing, it seems that it is more likely to fail when I select the item with the mouse rather than using the arrow keys. It won't fail if I narrow down the list to one item, but if there are multiple items and I click on one with the mouse, it does not seem to enter that item. Attached is a video showing it failing with the mouse and then working with the keyboard. 

https://user-images.githubusercontent.com/59976/177966919-9daa35d8-2d43-4cb6-bcf8-f974b1342fc8.mov

**Comment by sawhney17** [comment]
from what I can piece together it looks like if you click with the mouse, it will insert the currently highlighted ref, i.e. the last ref you selected with the keyboard.

**Comment by kerim** [comment]
It seems that while creating items with the keyboard alone solves some issues, it also creates others. For instance, the page template is only created properly when using the mouse, not the keyboard. In the latter case the metadata section of the template is not applied.
